//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailRecipient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmailRecipient()
        {
            this.ReportRecipients = new HashSet<ReportRecipient>();
        }
    
        public int pkEmailRecipientsID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> fkCreatedByUserID { get; set; }
        public string EmailAddress { get; set; }
        public string fkRecipientUserID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportRecipient> ReportRecipients { get; set; }
    }
}
